### PR TITLE
Added two functions for unread messages in thread

### PR DESCRIPTION
**Pull request by Kenny11CZ**
#80 #109
Two new functions:
userUnreadMessages($user_id)
userUnreadMessagesCount($user_i

### CODE REVIEW

**Comment by cmgmyr** [comment]
@Kenny11CZ thanks for the PR! I'll take a look at this over the weekend. Can you run this through the PSR2 formatter in the mean time? It would also be helpful to see some tests, but it's not required if you can't and/or don't have time. I can add them in later.

**Comment by Kenny11CZ** [comment]
So PSR-2 format is done, but i don't know how to do the test... Link me some websites, and I'll look at it.

**Comment by a-komarev** [comment]
Something like [free video tutorial for ](https://laracasts.com/series/phpunit-testing-in-laravel/episodes/12) or try to look for others by the word `phpunit`.

**Comment by Kenny11CZ** [comment]
So, I have added tests to QloquentThreadTest file. But i don't have clean laravel instalation so I can't run it... Can someone check it, if it is alright? For today I go sleep, it's 3am and I am very sleepy. gn..

**Comment by cmgmyr** [comment]
@Kenny11CZ can you please run: `vendor/bin/php-cs-fixer fix .` on your `master` branch, then commit/push the changes? Looks like there are a number of conflicts because of some formatting.

**Comment by Kenny11CZ** [comment]
Yeeeey, finaly made it merge-able...

**Comment by schonhose** [comment]
It would be great to see this merged.

**Comment by cmgmyr** [comment]
I'm going to merge this in, but I'm going to keep it in `master` for a while to do some more testing and make some small changes. Thanks again for the PR!

**Pull request merged**
