### PR TITLE
Bug missing prefix message

### PR DESCRIPTION
**Pull request by kenzouno1**

### CODE REVIEW

**Comment by a-komarev** [comment]
Could you cover it with unit test?

**Comment by a-komarev** [comment]
Ah... I have prefixes in config file:
```php
'messages_table' => 'messenger_message',
'participants_table' => 'messenger_participant',
'threads_table' => 'messenger_thread',
```

**Comment by a-komarev** [comment]
@kenzouno1 here I found a bit another approach:

https://github.com/cmgmyr/laravel-messenger/blob/0a1d2f7ff5f5bf7af4d7e27f995e6828eb6c4f81/src/Traits/Messagable.php#L79-L85

And here:
https://github.com/cmgmyr/laravel-messenger/blob/0a1d2f7ff5f5bf7af4d7e27f995e6828eb6c4f81/src/Models/Thread.php#L182-L194

```php
$this->getConnection()->getTablePrefix()
```

**Comment by kenzouno1** [comment]
```
    'messages_table' => 'messages',

    'participants_table' => 'participants',

    'threads_table' => 'threads',
```
here is my config.

**Pull request closed without merging**
