### PR TITLE
fix bug for composer update at first time

### PR DESCRIPTION
**Pull request by bagart**
php artisan optimize
  [Symfony\Component\Debug\Exception\FatalThrowableError]
  Class 'custom\Model\User' not found

### CODE REVIEW

**Comment by a-komarev** [comment]
@bagart can you show your messenger config file content?

**Comment by Promixius** [comment]
Should not check og the class exists because the user model is required to run this or at least a user class of some sort. 
So this will lead me to believe that you made a typo in your confit or the namespace you gave your user model. 
Or did you forget to update the user model namespace after you moved it to a new folder?

**Comment by bagart** [comment]
After all steps of setup my app is broken. 

after testing I catch:

I remove only 1 line in config/app.php - providers with MessengerServiceProvider without change other components like composer.json, routers with installed messanger and other messanger components(views, controoller)

run `composer update` and site is work. 
I past this line again and composer/sites is broken. and namespace in vendor/composer/autoload is empty. on error I have ~1000 lines in autoload_classmap.php. but 4100 lines when all is ok

step-by-step debug on composer.phar is too difficult and I just catch dependend line
I think: composer component of preparing autoload get fatal error and exit in silence mode

important thing: when I run composer update - this service booted many times! but crashes on prepare class mapping

I add in commposer.json `post-update-cmd` temporary dirty fix for this case and it's work, but too dirty
`            "sed -i -e 's/Models::setUserModel($model).*/Models::setUserModel($model); if (class_exists($model))/' vendor/cmgmyr/messenger/src/Cmgmyr/Messenger/MessengerServiceProvider.php",`


real resons of this bug can be in other required composer (devtools, for example). I ready to send conposer.json to private message.
but I never seen this before and think is not  acceptable

**Comment by bagart** [comment]
messenger config is default

**Comment by bagart** [comment]
I try to remove all other required components and service and get this error

```
{
    "name": "laravel/laravel",
    "require": {
        "php": ">=5.6.4",
        "laravel/framework": "5.3.*",
        "Cmgmyr/messenger": "dev-master"
    },

    "autoload": {
        "classmap": [
            "database"
        ],
        "psr-4": {
            "hinta\\": "hinta_app/"
        }
    },
    "scripts": {
        "post-update-cmd": [
            "php artisan optimize"
        ]
    }
}
```

and
"require": {
    "cmgmyr/messenger": "~2.0"
and get some error
```
laradock@f3db5632f335:/var/www$ composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Writing lock file
Generating autoload files
> php artisan optimize


  [Symfony\Component\Debug\Exception\FatalThrowableError]
  Class 'hinta\Model\User' not found


Script php artisan optimize handling the post-update-cmd event returned with error code 1

```

**Comment by a-komarev** [comment]
@bagart have you tried to perform `php artisan optimize` with messenger service provider commented out from `./config/app.php`?

**Comment by bagart** [comment]
1st commented, 2nd remove? it's  jock?

**Comment by a-komarev** [comment]
@bagart When I've got issues with not dumped classes - I temporary remove packages service providers which has conflicts, perform `composer dump` or `php artisan optimize` (as you wish) and then re-enable service providers.

**Comment by bagart** [comment]
I try to remove ALL components. and public stdout early

```
laradock@f3db5632f335:/var/www$ composer dump
Generating autoload files
laradock@f3db5632f335:/var/www$ cat vendor/composer/autoload_classmap.php |wc
    548    2710   57682
```
wrong line count. and I dont know why
but it's work on composer update with my patch

there is no 'exit' or 'die'
```
laradock@f3db5632f335:/var/www$ grep -rP '(dd|exit|die)[;\(]' config/
laradock@f3db5632f335:/var/www$ grep -rP '(dd|exit|die)[;\(]' app/
app/Providers/AppServiceProvider.php:            $event->menu->add('MAIN NAVIGATION');
app/Providers/AppServiceProvider.php:            $event->menu->add([
app/Providers/AppServiceProvider.php:                $event->menu->add(trans('menu.pages'));
app/Providers/AppServiceProvider.php:                $event->menu->add(...$items);
```

**Comment by bagart** [comment]
important:
```
    "scripts": {
        "post-update-cmd": [
            "php artisan optimize"
        ]
    }
```
post-update-cmd!
without this 'script' composer finished without error, but site is not work

**Comment by bagart** [comment]
not work
```
$ composer dump; cat vendor/composer/autoload_classmap.php |wc
Generating autoload files
    548    2710   57682

$ composer dump-autoload; cat vendor/composer/autoload_classmap.php |wc
Generating autoload files
    548    2710   57682

```
work:
```
$ composer dump-autoload -o;cat vendor/composer/autoload_classmap.php |wc
Generating optimized autoload files
   4114   20540  510696
```

work, but is not metter for `composer update` 

```
laradock@f3db5632f335:/var/www$ composer dump-autoload -o;cat vendor/composer/autoload_classmap.php |wc
Generating optimized autoload files
   4114   20540  510696
laradock@f3db5632f335:/var/www$ composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package guzzle/guzzle is abandoned, you should avoid using it. Use guzzlehttp/guzzle instead.
Writing lock file
Generating autoload files
> Illuminate\Foundation\ComposerScripts::postUpdate
> php artisan ide-helper:generate


  [Symfony\Component\Debug\Exception\FatalThrowableError]
  Class 'hinta\Model\User' not found

```

**Comment by bagart** [comment]
> After that all future dumps and optimizes will work without any manipulations.
my case with problem is different!
I know, my English is not well, but...

> .. you don't have your custom namespace in compiled autoload files yet...
`composer update` make autoload. and `composer update` is not work. what more?
app, site, `composer update` and `artisan optimize` work without this component!
my composer like official:
https://github.com/laravel/laravel/blob/master/composer.json
```
    "autoload": {
        "classmap": [
            "database"
        ],
        "psr-4": {
            "custom\\": "app/"
        }
    },
```

>If this thick will help - clean install with composer install will work on remote server without any issues too.
I published shorten version of composer.json without custom components(only code). remove path of vendor and composer.lock - but `composer update` still not work with same error! and real reason is `composer dump` of autoload is not full. 

real good way - remove cross-dependence on `composer update`

**Comment by Promixius** [comment]
Your going way wrong on this, you said you left your config default, well that wont work mister.
Take a look at the config of messenger:
`<?php
return [
    'user_model' => App\User::class,
    'message_model' => Cmgmyr\Messenger\Models\Message::class,
    'participant_model' => Cmgmyr\Messenger\Models\Participant::class,
    'thread_model' => Cmgmyr\Messenger\Models\Thread::class,
    /**
     * Define custom database table names.
     */
    'messages_table' => null,
    'participants_table' => null,
    'threads_table' => null,
];`
Well you see that user_model ?
You need to update that to be in your namespace so that would be
`'user_model' => custom\User::class,`
that is it.

**Comment by bagart** [comment]
I change my user user_model! 
before create this pull request

**Comment by bagart** [comment]
I found 1 more fix without sed
```
         "post-install-cmd": [
            "composer dump -o",
......        ],
        "post-update-cmd": [
            "composer dump -o",
......        ],
```
buy is so slow

**Comment by bagart** [comment]
my mistake is: path named like `custom/Models` but class named like `custom/Model`
=> autoload not work

**Comment by a-komarev** [comment]
@bagart glad you found a solution!

**Pull request closed without merging**
