### PR TITLE
added rewmoveParticipant($userId) method

### PR DESCRIPTION
**Pull request by theunreal**

### CODE REVIEW

**Comment by johannesschobel** [comment]
Hey there,
I really like the idea. However, to comply with the already existing `addParticipants(array)` method, I think, it would be better to create a `removeParticipants(array)` method.

What do you think?
Cheers

**Comment by cmgmyr** [comment]
@theunreal thanks for the PR! I'm going to go ahead and merge this in and work on it a bit more.

@johannesschobel Yes, I agree, but I'm also thinking about altering the API a bit more for both of those methods to `addParticipant` (dropping the "s") and `removeParticipant` which would both accept a single `id` or `array`. This is would be similar to Laravel's `dropColumn` for migrations.

**Comment by johannesschobel** [comment]
@cmgmyr 
thanks for your reply regarding this issue and PR. When do you think you will be able to release API changes (dropping the ```s```)?

**Comment by cmgmyr** [comment]
Not sure ATM, but probably within the next day or so. Do you need these sooner than later? Usually, new changes will stay in `master` for a bit, then tagged with a new minor version after a few more days to a week, depending on what else is pending.

**Comment by johannesschobel** [comment]
No, sometimes during the next week is perfectly fine for me ;)

**Pull request merged**
