### PR TITLE
define foreign keys in participants and messages tables

### PR DESCRIPTION
**Pull request by BjornvdLaan**
Foreign keys defined explicitly in the migrations for participants and messages tables

### CODE REVIEW

**Comment by a-komarev** [comment]
This a breaking changes and wouldn't be usable to already deployed applications. Maybe it's better to make it as new migrations and no updating existing ones?

**Comment by cmgmyr** [comment]
I actually had foreign keys in this package initially, but opted to remove them because they were causing too many issues with other DBs and systems. So unless there is good reason to put them back in, I'd rather keep them out

**Comment by a-komarev** [comment]
@cmgmyr Maybe there is a way to make a console generator for manually creating such migrations which will be optional?

**Comment by a-komarev** [comment]
@BjornvdLaan I expect issues with your latest commit. Because migrations don't use namespaces such class name `AddForeignKeys` could have possible conflicts with other packages. And as Chris said earlier there are issues with different databases because of this foreign keys, so if you wish to add them - the only way to create custom console command which will generate such a migration for users who want to have them too.

**Comment by cmgmyr** [comment]
I'm going to close this PR for now, but I did make a new ticket for `V3` to revisit this. Thank you for the PR @BjornvdLaan and your additional ideas and feedback @a-komarev!

**Comment by Juanperezc** [comment]
@antonkomarev 
How can I use that command? . I do not see the messeger option when I do

`php artisan list`

**Comment by antonkomarev** [comment]
@Juanperezc this is only concept how it could be implemented. But in fact there is no such command in the package. You could create migration with foreign keys in your app by yourself.

**Pull request closed without merging**
