### PR TITLE
Fixed last commit on Messagable trait

### PR DESCRIPTION
**Pull request by DODMax**
- New messages in unread thread were not showing
- Converting return value of threadsWithNewMessages to array as suggested by @Gummibeer
- Added test to cover the issue

### CODE REVIEW

**Comment by DODMax** [comment]
Not sure why the test I added is failing. I can't reproduce for now..

**Comment by a-komarev** [comment]
> \Test\MessagableTraitTest::it_should_get_all_threads_with_new_messages_last_read_null

> BadMethodCallException: Call to undefined method Illuminate\Database\Query\Builder::newMessagesCount()

Maybe because user don't have method `newMessagesCount` and have `newThreadsCount`?

**Comment by DODMax** [comment]
Though it work on the exact same test just before: it_should_get_all_threads_with_new_messages()

**Comment by cmgmyr** [comment]
I'm going to hold off on these changes for now.

**Pull request closed without merging**
