### PR TITLE
fix(thread): counting unread messages

### PR DESCRIPTION
**Pull request by BurningDog**
The userUnreadMessages() was counting messages I had sent as unread messages, but it should only count unread messages sent by somebody else.

### CODE REVIEW

**Comment by BurningDog** [comment]
Travis CI builds failed (but no environment variables are set). Scrutinizer failed because it couldn't get code coverage data. What do we do next?

**Comment by antonkomarev** [comment]
Only @cmgmyr could help in this question.

**Comment by cmgmyr** [comment]
@BurningDog thanks so much for your PR! It looks like you were missing the `$userId` from the use statement for the filter. I adjusted what you did slightly and put the userId check on the query instead of the collection filter. Feel free to try out `dev-master` when you get a chance.

**Comment by BurningDog** [comment]
Ah cool, that makes more sense - thanks!

**Pull request closed without merging**
