### PR TITLE
[WIP] scope between bug fix

### PR DESCRIPTION
**Pull request by cmgmyr**
So far this is the nicest solution that I've come up with, but it only successfully runs on mysql which isn't ideal, and is why I have the test deactivated (sqlite). I also ran locally with postgresql and failed.

As an alternative, the MySQL query that successfully runs is:

```mysql
SELECT DISTINCT
	(thread_id)
FROM
	participants a
WHERE
	user_id IN(1 , 2)
AND EXISTS(
	SELECT
		1
	FROM
		participants b
	WHERE
		a.thread_id = b.thread_id
	GROUP BY
		thread_id
	HAVING
		COUNT(DISTINCT user_id) = 2
)
GROUP BY
	thread_id
HAVING
	COUNT(thread_id) = 2
```

but this is a beast to try and run within the scope and Eloquent. I'm just posting this here to see if anyone else has any ideas or wants to take a crack at it. I'll keep pushing tomorrow.

### CODE REVIEW

**Comment by a-komarev** [comment]
I've described how this issue could be solved with more "light" queries in any database engine: https://github.com/cmgmyr/laravel-messenger/issues/209#issuecomment-282402653

But it will be only good for private messaging or very small chat rooms. Otherwise `participants` field will be type of `text` and as result it wouldn't be an optimized way.

**Comment by cmgmyr** [comment]
@a-komarev yeah, that's what I was trying to accomplish with the group concat and make it work dynamically without an extra column, but it doesn't work the same across db drivers. I'm still hopefully to find a dynamic solution that will work across the board without adding a bunch of complexity or more columns. Just wanted to throw some ideas out there

**Comment by cmgmyr** [comment]
@a-komarev let me know what you think of the latest changes when you get a chance.

I added a new `total_participants` column to the `Thread` model, which will get updated every time there is a new participant added. My opinionated implementation also includes (soft)deleted/archived participants, which I think seems expected.

I have to do a little cleanup/de-duplication, but everything seems to be working well so far.

**Comment by a-komarev** [comment]
Nice change, @cmgmyr.

As I understand this isn't actual `between` scope bug fix, it's an preparation for it which will simplify query, am I right?

First what I've thought about is to rename column from `total_participants` to `participants_count`. But then I've thought that we might need to have actual participants count (without deleted ones). I like the name, but usually I prefer to have `total` keyword at the end to have same naming convention:
- `participants_count` - thread actual participants count without trashed.
- `participants_total` - thread actual participants count with trashed.

Second what I've notice that you are using string table name in migration, and it should be replaced with configurable one. And Thread model too.

Replace:
```php
Schema::table('threads', function (Blueprint $table) {
```
With
```php
Schema::table(Models::table('threads'), function (Blueprint $table) {
```
// And same in `down` migration

And replace:
```php
foreach (Thread::withTrashed()->get() as $thread) {
```
With:
```php
foreach (Models::thread()->withTrashed()->get() as $thread) {
```

**Comment by a-komarev** [comment]
Why are you adding new column only not for test environment?
```php
if (App::environment() != 'testing') {
```

**Comment by cmgmyr** [comment]
@a-komarev I'll change to `participants_total` but not sure about adding another one for active participants (not soft-deleted). It seems like there would be too many potential use cases to use `total` or `active` with `scopeBetweenLoose` and scopeBetweenStrict`. Unless those default to just active, and either pass an optional flag, or have two different scopes for total participants with soft-deleted ones. What do you think?

The `if (App::environment() != 'testing') {` is just to update the data in the new column, so didn't seem needed to run in testing environments. Could remove I guess.

**Comment by a-komarev** [comment]
@cmgmyr let's imagine the situation. User1 joined the group and then left from it. But when I'll try to get all the threads where User1 and User2 are participating I will get even group from where User1 has left.

**Comment by a-komarev** [comment]
I think everybody will try to get threads where user is currently participating. And getting list where user was participant earlier is much rare use case. But as you said there are many cases for total count too, so flags seems to be reasonable.

**Comment by Gummibeer** [comment]
I think that the `participants` table adds an unnecessary complexity to the table structure. This table replaces a simple n:n pivot-table with another model and two 1:n relations.
So that you have to find the right participants for the users first instead of just asking for threads that occur in both user-thread pools with a participant/user count of 2.

So without the participants it would simple as (`withCount` was added in L5.3):

```php
Thread::withCount('users')->whereHas('users', function($query) use ($userIds) {
  return $query->whereIn('id', $userIds;)
})->having('users_count', 2)->first();
```

**Comment by Sunvers** [comment]
How is the status of the pull request? Is there any progress? 
Im using the scope to get the thread link between to users:
`
/** @var Collection $threads */
$threads = Thread::between([Auth::id(), $user->id])->get();

if($threads && $threads instanceof Collection && $threads->count() > 0) {
    /** @var Thread $thread */
    $thread = $threads->first();
    return l10n()->route('messages.show', ['id' => $thread->id]);
}

return l10n()->route('messages.create', ['id' => $user->id]);
`
Is this `$threads = Thread::between([Auth::id(), $user->id])->get();` working or should I add a custom scope until this pull request is merged?

**Comment by karlshea** [comment]
Here's another approach:

```php
function scopeBetweenStrict(Builder $query, array $participants)
{
    return $query->whereHas('participants', function (Builder $q) use ($participants) {
        $bindingsString = implode(',', array_fill(0, count($participants), '?'));

        $q->select('thread_id')
            ->groupBy('thread_id')
            ->havingRaw("SUM(user_id NOT IN ($bindingsString)) = 0", [$participants]);

        foreach ($participants as $participant) {
            $q->havingRaw('SUM(user_id = ?) = 1', [$participant]);
        }
    });
}
```

From [this StackOverflow thread](https://stackoverflow.com/questions/14113267/sql-select-only-rows-where-exact-multiple-relationships-exist).

**Comment by cmgmyr** [comment]
fixed in #359

**Pull request closed without merging**
